### ISSUE TITLE
PHP 8.2/8.1

### ISSUE THREAD

**Issue by juuf** [norment/redcap#19]
When using PHP 8.2 or 8.1 in for the web server, REDCap shows a blank screen after using our values in database.php. Might be relevant for future REDCap versions. 7.4 works fine for now.

**Comment by ofrei** [comment]
I've got this error on my local REDCap installation on a very basic API call (import_metadata), and it may be related to PHP versions, accoridng to this https://github.com/vanderbilt-redcap/cross-project-piping-module/issues/16
```
E       AssertionError: REDCap metadata import failed: status=400, body=				<div class="red" style="margin:20px 0px;max-width:700px;">
E         					<b>REDCap crashed due to an unexpected PHP fatal error!</b><br><br>
E         					<b>Error message:</b> Uncaught Exception: Prepared statement execution failed in redcap_v14.0.7/Classes/System.php:2457
E         Stack trace:
E         #0 redcap_v14.0.7/Config/init_functions.php(301): System::queryWithParameters()
E         #1 redcap_v14.0.7/Classes/MetaData.php(439): db_query()
E         #2 redcap_v14.0.7/API/metadata/import.php(17): MetaData::createDataDictionarySnapshot()
E         #3 redcap_v14.0.7/API/index.php(471): include('/var/www/html/r...')
E         #4 api/index.php(9): include('/var/www/html/r...')
E         #5 {main}
E           thrown<br>
E         					<b>File:</b> redcap_v14.0.7/Classes/System.php<br>
E         					<b>Line:</b> 2457<br>
E         				</div>
E         				{"error":"An unknown error occurred. Please check your API parameters."}
```

**Comment by ofrei** [comment]
resolved by #20
